# Generated by Django 4.2.1 on 2025-06-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_paid_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order'),
        ),
    ]
